name: e2e tests

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'PR number this workflow has been triggered from'
        required: false

  push:
    branches:
    - 'main'
    tags:
    - '*'

jobs:
  post-comment-in-pr:
    if: ${{ github.event.inputs.pr-number != '' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
      # URL is the current's workflow run URL
      URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
    - uses: actions/checkout@v3
    - run: gh pr comment ${PR_NUMBER} --body "E2E tests were started at ${URL}"
    - run: gh pr edit ${PR_NUMBER} --remove-label ci/run-e2e

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes-version:
        - 'v1.25.3'
        - 'v1.26.0'
    steps:
    - uses: actions/checkout@v3
    - run: sleep 10
    - run: ls -la
