name: e2e tests

on:
  workflow_dispatch: {}
  push:
    tags:
    - '*'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes-version:
        - 'v1.25.3'
        - 'v1.26.0'
    steps:
    - uses: actions/checkout@v3
    - run: ls -la
